# Generated by Django 5.2.3 on 2025-07-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_cart_cartitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["cart", "product__nome"],
                "verbose_name": "Item do carrinho",
                "verbose_name_plural": "Itens do carrinho",
            },
        ),
        migrations.AlterModelOptions(
            name="perfil",
            options={"verbose_name": "Perfil", "verbose_name_plural": "Perfis"},
        ),
        migrations.AddField(
            model_name="produto",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="produtos/"),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
